#! /bin/sh

sxhkd &
wal --theme base16-dracula &
tint2 &
volumeicon &
nm-applet & 
nitrogen --restore ; sleep 1 ; compton -b &
clipit &
pamac-tray &
xfce4-power-manager &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fix_cursor &
ff-theme-util &
unclutter --timeout 5 &



bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.

bspc config normal_border_color "$color0"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color15"

# Use the line below if you are on bspwm >kl= 0.9.4

bspc config presel_feedback_color "$color6"
